spring:
    application:
        name: et-gateway-service
    
    cloud:
        gateway:
            routes:
                -   id: et-event-microservice
                    uri: lb://et-event-microservice
                    predicates:
                        - Path=/api/v1/evenement/**
                -   id: et-internaute-microservice
                    uri: lb://et-internaute-microservice
                    predicates:
                        - Path=/api/v1/internaute/**
                -   id: et-ticket-microservice
                    uri: lb://et-ticket-microservice
                    predicates:
                        - Path=/api/v1/ticket/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true